[versions]

clikt = "3.5.2"
compose = "1.5.11"
#compose = "1.6.0-alpha01"
compose-stylesheet = "0.0.3"
exposed = "0.46.0"
jvmTarget = "17"
koin = "3.5.3"
kotlin = "1.9.21"
kotlinx-coroutines = "1.7.3"
#kotlinx-coroutines = "1.7.2-wasm0"
kotlinx-serializationJson = "1.6.2"
ktor = "2.3.7"
compose-lazyLayouts = "0.2.2"
slf4j = "2.0.11"
sqlite-jdbc = "3.44.1.0"

[libraries]

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
compose-lazyLayouts = { module = "dev.opensavvy.compose.lazy:lazy-layouts", version.ref = "compose-lazyLayouts" }
compose-stylesheet = { module = "com.moriatsushi.compose.stylesheet:compose-stylesheet", version.ref = "compose-stylesheet" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serializationJson" }
ktor-clientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
